---
site: bookdown::bookdown_site
documentclass: article
toc: false
citation_package: biblatex
bibliography: /Users/dietmar/Dropbox/zotero/Zotero.bib
csl: /Users/dietmar/Dropbox/zotero/styles/chicago-note-bibliography.csl
---

# Photography and other autographic acts

We live in a warming world, and yet, none of its living beings are directly affected by the climate---they only care about the weather.[^index-1] As humans, likewise, we can never experience the climate itself: it is a statistical concept, or as the philosopher Timothy Morton puts it, a *hyperobject* distributed in space and time.[@morton2013] While science is concerned with the bigger picture---long-term trends that only become visible through statistical generalizations---the same abstractions cause endless public confusions and disinformation. "It is only a model" is the rallying cry of climate skeptics, as if mathematical representations of complex natural systems could be anything else. Climate and weather are often conflated, leading to speculations if certain extreme weather events prove or disprove global warming. The public awareness of a heating planet is hampered by the fact that we cannot perceive the climate, only the weather. But not all hope is lost, at least in this regard: as Morton also points out, *hyperobjects* such as the climate tend to leave footprints everywhere, and these footprints can be perceived and aesthetically experienced: shrinking glaciers and countless other traces in our environment. Tree rings and ocean sediments are natural forms of statistical aggregation---the impacts of many small weather events condensed into physical patterns that form over decades, centuries, and millennia.

Our present intellectual culture, however, has largely stopped paying attention to physical traces. They are merely the starting points of data sets and rhetorical arguments. We tend to consider traces only in mediated and highly processed form, for example, as digital photographs supporting evidentiary claims. This has not always been the case. The epistemology of the late 19^th^ century was obsessed with traces, imprints, and inscriptions. As Henry Thoreau roamed the forests around Walden and Cape Cod, he never failed to report traces he encountered, from animal tracks to native-american arrowheads. Contemplating a tree stump of a freshly cut tree, he notes: "See how many traces from which we may learn the chopper's history. From this stump we may guess the sharpness of his axe, and, from the slope of the stroke, on which side he stood, and whether he cut down the tree without going round it or changing hands; and, from the flexure of the splinters, we may know which way it fell. This one chip contains inscribed on it the whole history of the wood-chopper and of the world."[@thoreau2011, p. 61] Contemplating found arrowheads, the word *mindprint* comes to him: "They are not fossil bones, but, as it were, fossil thoughts, forever reminding me of the mind that shaped them."[@thoreau2011a, p. 557] The boundaries between text and trace, author and the world are fluid for Thoreau; writing is always also an act of self-writing, or autography, producing a plethora of unintentional traces.[See @garber2014]

Although Thoreau may have seemed like an eccentric figure, many of his contemporaries shared a similar perspective on the world. Historian Carlo Ginzburg calls this epistemology the *conjectural paradigm*, a method of reasoning based on the close reading of clues. He finds it in the methods of the art critic Giovanni Morelli, the psychoanalyst Sigmund Freud, and the fictional detective Sherlock Holmes.[@ginzburg1980] The three share a taste for seemingly insignificant details, which lead them to significant discoveries. Morelli can identify forged portraits based on the style of an ear or a hand. Freud attaches great significance to every carelessly spoken word, and Holmes pays attention even to absent traces, such as the dog that did not bark when the owner's horse was stolen. Ginzburg locates the origins of this epistemology of traces in the advances of medical diagnostics---Morelli, Freud, and Arthur Conan Doyle were all physicians by training, attuned to the interpretation of symptoms as indicators of underlying conditions.

But one could argue that there is another cultural phenomenon contributing perhaps more directly to the fascination with the trace: photography and its emergence as a mass medium in the second half of the 19^th^ century. No other method of trace-making and self-inscription produces such a vivid result. An imprint of the world appears seemingly out of nowhere and without human contact. Of course, none of this is unfamiliar. The dual life of a photograph as a picture and a physical trace---or in semiotic terms, as an icon and an index---is a well-worn trope in media theory. But while the contemporary discourse around photography tends to take its materiality for granted, the early days were still captivated by the optical-chemical process itself---Henry Fox Talbot describes it as the pencil of nature. The photographic trace becomes an epistemic metaphor: it is only a small step to compare the darkening silver halide crystals that can capture an image of reality to learning and knowledge production. After all, are not all human memories, knowledge, and desires essentially imprints in the human body and mind?

Similar to a photographic plate, also the earth is a sensitive surface that records everything that has taken place. Transcendentalist poet Ralph Waldo Emerson wrote in 1850: "Nature will be reported. All things are engaged in writing their history. The planet, the pebble, goes attended by its shadow. The rolling rock leaves its scratches on the mountain; the river its channel in the soil; the animal its bones in the stratum; the fern and leaf their modest epitaph in the coal."[@emerson1901, p. 203] The trace becomes an all-encompassing metaphor for material information and the basis for an epistemology that blurs dichotomies such as the boundary between the human body and the world, intentional acts and non-human processes, human thoughts and material interactions---concerns that have only recently reemerged in new materialism and the feminist philosophy of Karen Barad.

If we, as the curators of the festival invite us, turn our attention to the communication channels offered by the planet itself and take it seriously as a force for producing images, then what is the role of the human designer? If we pay attention to planetary diagrams, the footprints of global warming as they present themselves rather than being content with mediated data representations, what kind of visualization practice do they constitute or require? As I have argued elsewhere, the perspective of autographic visualization is in many ways a countermodel to data visualization.

An autographic perspective decenters visualization practices away from human - as with Thoreau, the focus is not primarily on *what* is written---i.e. the semiotic concern for the many dimensions of meaning---but on *how*. a curiosity focused on the material interactions.

The emergence of the digital image has again complicated the trace-like, indexical nature of the photograph and its ability to support evidentiary claims. Also the iconicity of the digital image has received new scrutiny, expressed in discussions around whether a satellite image should even be compared to a photograph, as it is a sythetic product of algorithms operating on numerical measurements.

But I believe it is worthwhile to We should return - no longer what the photographic trace signifies, but what it shares with other forms of inscription.

Autography - the act of self inscription. How the world records its own history. Semiotics tends to distance us from the physicality of the process, and move us closer to language and questions of interpretation.

photography - trygg, nahrinen - photography, image making with the planet

connection to the mind -

but from perspective of autographic visualization, these seemingly difficult and fraught issues are not relevant. Both chemical photo and the satellite image are physical traces in the same sense. the only difference is the complexity of the apparatus in between. And in this sense, both share qualities with the layers in the ice core, the shrinking of the glacier, the tree rings ... the planetary self-inscriptions, in which processes manifest themselves - processes that rival or exceed the complexity of the satellite imaging device.

goal is to return from issues of cultural signification to more curiosity

not just about what is written (including the many layers of meaning), but also about how.

[^index-1]: As marine scientist Brian Helmuth notes, increases in mean temperature over decades (i.e., climate) are not the proximate drivers of performance and survival at the scale of the organisms. Their vulnerability is affected by short term variations (i.e. weather) including extreme events that are implicit in climatic predictions. See @helmuth2014, p. 2
